### ISSUE TITLE
[FEATURE] Make the commands of this mod available from the created datapacks.

### ISSUE THREAD

**Issue by nea-c** [eclipseisoffline/customname#6]
**Is your feature request related to a problem? Please describe.**
I want to write a process to automatically change nicknames from a datapacks.

**Describe the solution you'd like, or the feature you want to see implemented**
If the nickname can be changed from the datapack or command block, then there is no need to run the command manually.

**Comment by eclipseisoffline** [comment]
This is actually a bug - I did intend on making certain commands available to command blocks/datapacks/the server console, but made a small mistake in setting up the commands.

With the next release of the mod,

- People can be named by datapacks using `name other <nickname|prefix|suffix> <player>` or `execute as <player> run name <nickname|prefix|suffix>`
- People's item's name/lore can be changed using `execute as <player> run itemname <name>` or `execute as <player> run itemlore <lore>`
